/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdCategoriesCategoryIdIndexRouteImport } from './routes/projects/$projectId/categories/$categoryId/index'
import { Route as ProjectsProjectIdCategoriesCategoryIdSettingsRouteImport } from './routes/projects/$projectId/categories/$categoryId/settings'
import { Route as ProjectsProjectIdCategoriesCategoryIdOverviewRouteImport } from './routes/projects/$projectId/categories/$categoryId/overview'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdCategoriesCategoryIdIndexRoute =
  ProjectsProjectIdCategoriesCategoryIdIndexRouteImport.update({
    id: '/projects/$projectId/categories/$categoryId/',
    path: '/projects/$projectId/categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdCategoriesCategoryIdSettingsRoute =
  ProjectsProjectIdCategoriesCategoryIdSettingsRouteImport.update({
    id: '/projects/$projectId/categories/$categoryId/settings',
    path: '/projects/$projectId/categories/$categoryId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdCategoriesCategoryIdOverviewRoute =
  ProjectsProjectIdCategoriesCategoryIdOverviewRouteImport.update({
    id: '/projects/$projectId/categories/$categoryId/overview',
    path: '/projects/$projectId/categories/$categoryId/overview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId/categories/$categoryId/overview': typeof ProjectsProjectIdCategoriesCategoryIdOverviewRoute
  '/projects/$projectId/categories/$categoryId/settings': typeof ProjectsProjectIdCategoriesCategoryIdSettingsRoute
  '/projects/$projectId/categories/$categoryId/': typeof ProjectsProjectIdCategoriesCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId/categories/$categoryId/overview': typeof ProjectsProjectIdCategoriesCategoryIdOverviewRoute
  '/projects/$projectId/categories/$categoryId/settings': typeof ProjectsProjectIdCategoriesCategoryIdSettingsRoute
  '/projects/$projectId/categories/$categoryId': typeof ProjectsProjectIdCategoriesCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId/categories/$categoryId/overview': typeof ProjectsProjectIdCategoriesCategoryIdOverviewRoute
  '/projects/$projectId/categories/$categoryId/settings': typeof ProjectsProjectIdCategoriesCategoryIdSettingsRoute
  '/projects/$projectId/categories/$categoryId/': typeof ProjectsProjectIdCategoriesCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId/categories/$categoryId/overview'
    | '/projects/$projectId/categories/$categoryId/settings'
    | '/projects/$projectId/categories/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId/categories/$categoryId/overview'
    | '/projects/$projectId/categories/$categoryId/settings'
    | '/projects/$projectId/categories/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId/categories/$categoryId/overview'
    | '/projects/$projectId/categories/$categoryId/settings'
    | '/projects/$projectId/categories/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ProjectsProjectIdCategoriesCategoryIdOverviewRoute: typeof ProjectsProjectIdCategoriesCategoryIdOverviewRoute
  ProjectsProjectIdCategoriesCategoryIdSettingsRoute: typeof ProjectsProjectIdCategoriesCategoryIdSettingsRoute
  ProjectsProjectIdCategoriesCategoryIdIndexRoute: typeof ProjectsProjectIdCategoriesCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/categories/$categoryId/': {
      id: '/projects/$projectId/categories/$categoryId/'
      path: '/projects/$projectId/categories/$categoryId'
      fullPath: '/projects/$projectId/categories/$categoryId/'
      preLoaderRoute: typeof ProjectsProjectIdCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/categories/$categoryId/settings': {
      id: '/projects/$projectId/categories/$categoryId/settings'
      path: '/projects/$projectId/categories/$categoryId/settings'
      fullPath: '/projects/$projectId/categories/$categoryId/settings'
      preLoaderRoute: typeof ProjectsProjectIdCategoriesCategoryIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/categories/$categoryId/overview': {
      id: '/projects/$projectId/categories/$categoryId/overview'
      path: '/projects/$projectId/categories/$categoryId/overview'
      fullPath: '/projects/$projectId/categories/$categoryId/overview'
      preLoaderRoute: typeof ProjectsProjectIdCategoriesCategoryIdOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ProjectsProjectIdCategoriesCategoryIdOverviewRoute:
    ProjectsProjectIdCategoriesCategoryIdOverviewRoute,
  ProjectsProjectIdCategoriesCategoryIdSettingsRoute:
    ProjectsProjectIdCategoriesCategoryIdSettingsRoute,
  ProjectsProjectIdCategoriesCategoryIdIndexRoute:
    ProjectsProjectIdCategoriesCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
